# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  # utilities
  - name: util
    before: | 
      sudo apt-get install tree
  - name: powershell
    before: |
      ./bin/powershell_cli_install.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
  - name: terraform 
    before: |
      ./bin/terraform_cli_install.sh
      cd s3/iac/terraform/
  - name: cdk 
    before: |
     npm i -g aws-cdk
     cd s3/iac/cdk/
     yarn add aws-cdk-lib
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
