#!/usr/bin/env bash

# Check if the first argument is provided for filename prefix
if [ -z "$1" ]; then
    echo "First - filename prefix argument not provided. Usage: ./create_tmpfiles my_filename_prefix"
else
    echo "First argument - filename prefix: $1"
fi

FILENAME_PREFIX=$1;

# Exit immediately if any command returns a non-zero status
set -e 

# temporary directory
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Check if the directory exists
if [ -d "$OUTPUT_DIR" ]; then
    echo "$OUTPUT_DIR already exists. Hence deleting "
    # remove the folder if already existis
    rm -r $OUTPUT_DIR
else
    echo "$OUTPUT_DIR does not exist. Hence creating "
    # create the output folder
    mkdir -p $OUTPUT_DIR
fi


# Generate a random number between 5 and 10 to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

# Loop to create random files
for ((i=1; i<=NUM_FILES; i++)); do
    # generate a random filename
    FILE_NAME="$OUTPUT_DIR/${FILENAME_PREFIX}_${i}.txt"

    echo $FILE_NAME
    # generate random date and write it to the file
    dd if=/dev/urandom of="$FILE_NAME" bs=1024 count=$((random % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR
