#!/usr/bin/env bash

# Check if the First - bucket name and/or second - filepath  argument not provided
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "First - bucket name and/or second - filepath argument not provided."
else
    echo "First argument - bucket name: $1"
    echo "Second argument - filepath: $2"
fi

BUCKET_NAME=$1;
FILE_FULLPATH=$2;

# Check if the FILE_FULLPATH exists
if [ -e "$FILE_FULLPATH" ]; then
    # Check if it's a regular file
    if [ -f "$FILE_FULLPATH" ]; then
        echo "$FILE_FULLPATH is a regular file."
    # Check if it's a directory
    elif [ -d "$FILE_FULLPATH" ]; then
        echo "$FILE_FULLPATH is a directory."
    else
        echo "$FILE_FULLPATH is neither a file nor a directory."
        exit 
    fi
else
    echo "$FILE_FULLPATH does not exist."
    exit 
fi

# Exit immediately if any command returns a non-zero status
set -e 

  echo "Files in $FILE_FULLPATH to be uplodaded to s3 bucket $BUCKET_NAME:"
tree $OUTPUT_DIR

aws s3 sync $FILE_FULLPATH s3://$BUCKET_NAME/files
if [ $? -eq 0 ]; then
    echo "sync  executed successfully."
else
    echo "sync failed with exit code $?."
fi