#!/usr/bin/env bash

echo "=== Deploy S3 bucket via CloudFormation (CFN)"
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy.html
#  NOTE: should run the file from the location where template.yaml is availale eg: cd s3/iac/cfn/
#  --no-execute-changeset  is set your stack changes needs to be reviewed before executing the change set to create the stack
STACK_NAME="cfn-s3-simple-stack"

aws cloudformation deploy \
    --template-file template.yaml \
    --no-execute-changeset \ 
    --region us-east-1 \
    --stack-name $STACK_NAME 